# Generated by Django 5.0.3 on 2024-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studyportalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlog',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'adminlogin',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(max_length=18)),
            ],
            options={
                'db_table': 'S_contact',
            },
        ),
        migrations.CreateModel(
            name='Studentregister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=8)),
                ('sname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('passw', models.CharField(default='', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='upload')),
                ('term', models.CharField(max_length=10)),
                ('dt', models.CharField(default='', max_length=18)),
            ],
            options={
                'db_table': 'S_registration',
            },
        ),
    ]
